use emp;
create table persons(
PERSON_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
AGE INT NOT NULL);

INSERT INTO PERSONS VALUES
(1,'KASAK','PATEL',20);
INSERT INTO PERSONS VALUES
(2,'KAVYA','PATEL',18);
INSERT INTO PERSONS VALUES
(3,'MOXA','PATEL',19);
INSERT INTO PERSONS VALUES
(4,'MAULI','PATEL',18);
SELECT * FROM PERSONS;
CREAT TABLE ORDERS(
ORDER_ID INT NOT NULL,
ORDER_NUMBER INT NOT NULL,
PERSON_ID INT 
);


